require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe MembershipsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Membership. As you add validations to Membership, be sure to
  # adjust the attributes here as well.

  let(:new_member_params){
    {email: "validEmailNewMember@mail.com", email_confirmation: "validEmailNewMember@mail.com", name: "New Member",
      password: "password", password_confirmation: "password"}
  }

  let(:new_member){
    create :user, new_member_params
  }

  let(:owner){
    create :user
  }

  let(:book){
    create :book, user: owner
  }

  let(:valid_attributes) {
    {email: new_member.email, member: new_member, book: book, book_id: book.id}
  }

  let(:invalid_attributes) {
    {email: "invalidEmailMember@mail.com", member: new_member, book_id: book.id, book: book}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MembershipsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all memberships as @memberships" do
      @token = AuthenticateUser.call(new_member.email, new_member.password)
      request.headers["Authorization"] = @token.result

      membership = Membership.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:memberships)).to eq([membership])
    end
  end

  describe "GET #show" do
    it "assigns the requested membership as @membership" do
      @token = AuthenticateUser.call(new_member.email, new_member.password)
      request.headers["Authorization"] = @token.result

      membership = Membership.create! valid_attributes
      get :show, params: {id: membership.to_param}, session: valid_session
      expect(assigns(:membership)).to eq(membership)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Membership" do
        @token = AuthenticateUser.call(new_member.email, new_member.password)
        request.headers["Authorization"] = @token.result

        expect {
          post :create, params: {membership: valid_attributes}, session: valid_session
        }.to change(Membership, :count).by(1)
      end

      it "assigns a newly created membership as @membership" do
        @token = AuthenticateUser.call(new_member.email, new_member.password)
        request.headers["Authorization"] = @token.result

        post :create, params: {membership: valid_attributes}, session: valid_session
        expect(assigns(:membership)).to be_a(Membership)
        expect(assigns(:membership)).to be_persisted
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved membership as @membership" do
        @token = AuthenticateUser.call(new_member.email, new_member.password)
        request.headers["Authorization"] = @token.result

        post :create, params: {membership: invalid_attributes}, session: valid_session
        expect(assigns(:membership)).to be_a_new(Membership)
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested membership" do
      @token = AuthenticateUser.call(new_member.email, new_member.password)
      request.headers["Authorization"] = @token.result

      membership = Membership.create! valid_attributes
      expect {
        delete :destroy, params: {id: membership.to_param}, session: valid_session
      }.to change(Membership, :count).by(-1)
    end
  end

end
