require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe UsersController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # User. As you add validations to User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {:name => "ValidName",
    :email => "validEmail@mail.com",
    :email_confirmation => "validEmail@mail.com",
    :password => "validpassword",
    :password_confirmation => "validpassword"}
  }

  let(:invalid_attributes) {
    {:name => "ValidName",
    :email => "invalid email with spaces @ mail .com",
    :email_confirmation => "invalid email with spaces @ mail .com",
    :password => "validpassword",
    :password_confirmation => "validpassword"}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all users as @users" do

      user = FactoryGirl.create :user
      @token = AuthenticateUser.call(user.email, user.password)
      request.headers["Authorization"] = @token.result
      get :index, params: {}, session: valid_session

      expect(assigns(:users)).to eq([user])
    end
  end

  describe "GET #show" do
    it "assigns the requested user as @user" do

      user = FactoryGirl.create :user

      @token = AuthenticateUser.call(user.email, user.password)
      request.headers["Authorization"] = @token.result
      get :show, params: {id: user.to_param}, session: valid_session
      expect(assigns(:user)).to eq(user)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new User" do
        expect {
          post :create, params: {user: valid_attributes}, session: valid_session
        }.to change(User, :count).by(1)
      end

      it "assigns a newly created user as @user" do
        post :create, params: {user: valid_attributes}, session: valid_session
        expect(assigns(:user)).to be_a(User)
        expect(assigns(:user)).to be_persisted
      end

      it "returns the user auth_token once its created" do
        post :create, params: {user: valid_attributes}, session: valid_session

        expect(response).to have_http_status(:created)
        expect(response.headers["auth_token"]).not_to be(nil)
        expect(response.headers["auth_token"]).to be_kind_of(String)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved user as @user" do
        post :create, params: {user: invalid_attributes}, session: valid_session
        expect(assigns(:user)).to be_a_new(User)
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        {:name => "newValid Name",
        :email => "newValidEmail@mail.com",
        :email_confirmation => "newValidEmail@mail.com",
        :password => "validpassword",
        :password_confirmation => "validpassword"}
      }

      it "updates the requested user" do

        user = FactoryGirl.create :user

        @token = AuthenticateUser.call(user.email, user.password)
        request.headers["Authorization"] = @token.result
        put :update, params: {id: user.to_param, user: new_attributes}, session: valid_session
        user.reload
        expect(user.name).to eq(new_attributes[:name])
      end

      it "assigns the requested user as @user" do

        user = FactoryGirl.create :user

        @token = AuthenticateUser.call(user.email, user.password)
        request.headers["Authorization"] = @token.result
        put :update, params: {id: user.to_param, user: valid_attributes}, session: valid_session
        expect(assigns(:user)).to eq(user)
      end

      it "return the user once it is created" do

        user = FactoryGirl.create :user

        @token = AuthenticateUser.call(user.email, user.password)
        request.headers["Authorization"] = @token.result
        put :update, params: {id: user.to_param, user: valid_attributes}, session: valid_session
        expect(response).to have_http_status(200)
      end
    end

    context "with invalid params" do
      it "assigns the user as @user" do

        user = FactoryGirl.create :user

        @token = AuthenticateUser.call(user.email, user.password)
        request.headers["Authorization"] = @token.result
        put :update, params: {id: user.to_param, user: invalid_attributes}, session: valid_session
        user.reload
        expect(user.email).not_to eq(invalid_attributes[:email])
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested user" do

      user = FactoryGirl.create :user

      @token = AuthenticateUser.call(user.email, user.password)
      request.headers["Authorization"] = @token.result
      expect {
        delete :destroy, params: {id: user.id}, session: valid_session
      }.to change(User, :count).by(-1)
    end

  end
end
